name: Main CI - install, test, make and create release on tag

on:
  push:
    branches: [ master ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ master ]

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Package and make Windows installer
        run: npm run make
      - name: Upload installer as artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: out/make/squirrel.windows/x64/*.exe
          retention-days: 3

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install ImageMagick
        run: |
          brew update
          brew install imagemagick
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run unit tests
        run: npm test
      - name: Package Electron app
        run: npm run package
      - name: Run E2E tests
        run: npm run e2e
      - name: Make MacOS installer
        run: npm run make
      - name: Upload installer as artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-installer
          path: out/make/*.dmg
          retention-days: 3

  make-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ build-windows, build-macos ]
    steps:
      - name: Download installers
        uses: actions/download-artifact@v3
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-installer/*.exe
            macos-installer/*.dmg
          generate_release_notes: true
          draft: true
