name: Main CI - install, test, make and create release on tag

on:
  push:
    branches: [ master ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
    - name: Package and make Windows installer
      run: npm run make
    - name: Create release (only on tag)
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: out/make/squirrel.windows/x64/*.exe
        generate_release_notes: true
        draft: true
