name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 9 * * 1'  # Weekly on Mondays at 9 AM UTC
  workflow_dispatch:

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install ImageMagick
        run: choco install imagemagick
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run unit tests
        run: npm test
      - name: Package Electron app
        run: npm run package
      - name: Run E2E tests
        run: npm run e2e
      - name: Upload E2E test results as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-e2e-test-results
          path: test-results/
          retention-days: 3
      - name: Make Windows installer
        run: npm run make
      - name: Upload installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: out/make/squirrel.windows/x64/*.exe
          retention-days: 3

#  build-macos:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
#      - name: Setup Node.JS
#        uses: actions/setup-node@v4
#        with:
#          node-version-file: '.node-version'
#          cache: 'npm'
#      - name: Install ImageMagick
#        run: brew install imagemagick
#      - name: Install dependencies
#        run: npm ci
#      - name: Lint
#        run: npm run lint
#      - name: Run unit tests
#        run: npm test
#      - name: Package Electron app
#        run: npm run package
#      - name: Run E2E tests
#        run: npm run e2e
#      - name: Upload E2E test results as artifacts
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: macos-e2e-test-results
#          path: test-results/
#          retention-days: 3
#      - name: Make MacOS installer
#        run: npm run make
#      - name: Upload installer as artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: macos-installer
#          path: out/make/*.dmg
#          retention-days: 3

  release-scheduled:
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
