name: Main CI - install, test, make and create release on tag

on:
  push:
    branches: [ master ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ master ]

jobs:

  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test

  build-windows:
    runs-on: windows-latest
    needs: prebuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Package and make Windows installer
        run: npm run make
      - name: Upload installer as artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: out/make/squirrel.windows/x64/*.exe

  build-macos:
    runs-on: macos-latest
    needs: prebuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Package and make MacOS installer
        run: npm run make
      - name: Upload installer as artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-installer
          path: out/make/*.dmg

  make-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ build-windows, build-macos ]
    steps:
      - name: Download installers
        uses: actions/download-artifact@v3
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-installer/*.exe
            macos-installer/*.dmg
          generate_release_notes: true
          draft: true
